apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-helm-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: .
    repoURL: https://github.com/adyb-fj-cns/example-helm-app.git
    targetRevision: HEAD