{{- range .Values.clusters }}
apiVersion: v1
kind: Namespace
metadata:
  name: example-helm-app
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{printf "%s-%s" .name "example"}}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: {{ .destinationServer }}
  project: default
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
  source:
    path: .
    repoURL: https://github.com/adyb-fj-cns/example-helm-app.git
    targetRevision: HEAD
---
{{- end }}