apiVersion: v1
kind: Namespace
metadata:
  name: example-helm-app
---
apiVersion: v1
kind: Namespace
metadata:
  name: dummy
---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: example-helm-app
#  namespace: argocd
  #finalizers: []
#  finalizers:
#  - resources-finalizer.argocd.argoproj.io
#spec:
#  destination:
#    namespace: default
#    server: {{ .Values.spec.destination.server }}
#  project: default
#  syncPolicy:
#    automated: {}
#  source:
#    path: .
#    repoURL: https://github.com/adyb-fj-cns/example-helm-app.git
#    targetRevision: HEAD